### ISSUE TITLE
How to prevent students being notified of posts to blog

### ISSUE THREAD

**Issue by pmakinson** [moodleou/moodle-mod_oublog#49]
Hi,

We currently use the OUBlog on our 2.7 installation of Moodle. Currently we are experiencing an issue where the blog notifies all students in a class that a blog post has been made, using the moodle.com/my/ section.

We have the OUBlog set up as Separate Individual Blogs as this is an assessed activity.

The above is causing some confusion as students will click on the notification they are getting to see there is no new post, however I know from the admin side that posts have been made by other students. 

Is there a simple way to turn this off, or change to prevent students from seeing this notification unless they have posted. The ideal would be that when a tutor gives feedback that a notification is given rather than everytime a change is made?

Thanks in advance
Phil.

**Comment by jason-platts** [comment]
This is a known issue, see: https://github.com/moodleou/moodle-mod_oublog/issues/43

Currently there are no plans to fix this, it's one of those "if we have some free time" bugs.

I might be able to do a quick fix where group and individual blogs are removed from the list.

oublog_print_recent_activity() is the culprit here if you have access to code you can fiddle with this to stop displaying (returning) anything.

Closing this issue as duplicate see #43 for updates
